author: 百年孤独
title: 大道至简

baseurl: "/"
url: "http://imjcker.com"

# Build settings
#theme: minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# disqus 评论插件
disqus:
  shortname: imjcker

# 是否显示预览信息
show_excerpts: true

# 自定义变量
imjcker:
  menu: 首页

# 社交信息
social:
  qq: 570577029
  wechat: QQ570577029
  twitter_username: helloalanturing
  github_username: imjcker
  email: helloalanturing@icloud.com

# 样式设置
style:
  home:
    card_img: avatar.jpg
  css:
    tags_index: ['dark']
    tag_style: ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'dark']

# 谷歌分析
google_analytics: UA-164703783-1


