
author: 百年孤独
title: imjcker
email: helloalanturing@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  全栈工程师,大数据,人工智能专家,单身万岁!!!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blog.imjcker.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: helloalanturing
github_username:  imjcker

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

disqus:
  shortname: imjcker

# 分页
paginate: 8

show_excerpts: true

# 自定义变量
imjcker:
  menu: 首页
