author: 百年孤独
title: 大道至简

baseurl: "/"
url: "http://imjcker.com"

# 插件
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# 是否显示预览信息
show_excerpts: true

# 社交信息
social:
  qq: 570577029
  wechat: QQ570577029
  twitter_username: helloalanturing
  github_username: imjcker
  email: helloalanturing@icloud.com
  csdn: u012137018

# 样式设置
style:
  home:
    avatar: avatar.jpg
  css:
    tag_style: ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'dark']

graph:
  option:
    title:
      text: 知识图谱
      subtext: 单击文章节点跳转至指定文章页面，双击标签/分类，展示指定标签/分类的图谱信息
